language: r
sudo: false
cache: packages
file_glob: true
latex: false
pandoc: false
warnings_are_errors: true

r-packages:
  - roxygen2

r_github_packages:
  - kingaa/pomp@zero_tolerance

addons:
  apt:
    packages:
    - libgit2-dev
  homebrew:
    packages:
    - libgit2

stages:
- name: test
  if: tag IS blank
- name: coverage
  if: tag IS blank

jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: 3.5.0
    os: linux
  - r: release
    os: osx
  - stage: coverage
    r: release
    os: linux
    r_packages:
    - covr
    script:
    - travis_wait 30 Rscript -e 'covr::codecov()'
