project:
  type: website
  output-dir: docs
  resources: 
    - html/*
    - help/*
    - NEWS.html
    - R.css

website:
  title: "panelPomp"
  navbar:
    right:
      - icon: github
        href: https://github.com/cbreto/panelPomp
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: bibliography.qmd
        text: Bibliography
      - href: html/00Index.html
        text: Manual

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



