---
title: "panelPomp"
subtitle: "Inference for Panel Partially Observed Markov Processes"
format:
  html:
    code-links:
      - text: GitHub Source
        icon: github
        href: https://github.com/cbreto/panelPomp
    other-links:
      - text: pomp package 
        href: https://kingaa.github.io/pomp
        icon: link
      - text: spatPomp package 
        href: https://kidusasfaw.github.io/spatPomp
        icon: link
      - text: Download ZIP 
        href: https://github.com/cbreto/panelPomp/zipball/master
        icon: file-zip
      - text: Download TAR Ball 
        href: https://github.com/cbreto/panelPomp/tarball/master
        icon: file-zip
---

```{r, echo=FALSE}
library(desc)

# Read the DESCRIPTION file
desc_info <- description$new("../DESCRIPTION")

version <- data.frame(
  location = c("[GitHub](https://github.com/cbreto/panelPomp)", 
                "[CRAN](https://cloud.r-project.org/web/packages/panelPomp/index.html)"),
  version = c(desc_info$get('Version'), utils::available.packages(contriburl = utils::contrib.url('https://cloud.r-project.org'))['panelPomp', 'Version'])
)
rownames(version) <- NULL
```

#### Authors and Contributors

```{r, echo=FALSE}
# Get the authors data
authors <- desc_info$get_authors()
roles <- unlist(sapply(authors, function(x) paste0('[', paste0(x$role, collapse = ', '), ']')))
# Getting first and last name, and email if it is in the description. 
authors_list <- unlist(lapply(authors, function(author) {
  if (!is.null(author$email)) {
    paste(
      paste0(
        paste(
          paste(
            author$given, collapse = ' '
          ),  gsub("Breto","Bret\u00F3", author$family)
        ), " (", author$email, ")"
      ), paste0('[', paste0(author$role, collapse = ', '), ']')
    )
  } else {
    paste(paste(paste(author$given, collapse = ' '), author$family), paste0('[', paste0(author$role, collapse = ', '), ']'))
  }
}))
authors_txt <- paste(authors_list[1:(length(authors_list)-1)], collapse = ', ')
authors_txt <- paste(authors_txt, authors_list[length(authors_list)], sep = ', and ')
```

`r authors_txt`.

#### Version 

```{r, echo=FALSE}
version |> knitr::kable(col.names = NULL)
```

#### Package Description

`r gsub("Breto", "Bret\u00F3", desc_info$get('Description'))`

#### Depends

```{r, echo=FALSE}
desc_info$get_deps() |> knitr::kable()
```

#### License 

`r desc_info$get('License')`


